; 0 represents disable, 1 represents enable
[EfuseSettings]
Enable = 1
SettingsEnable = 0
LockEnable = 0
ReadBackEnable = 0
EfuseXmlPath=206AC-efuse_oppo6769.xml
auth_sv5Path=auth_sv5.auth
daa_open = 1
